service: jementory-api

provider:
 name: aws
 runtime: nodejs14.x
 stage: ${opt:stage, "dev"}
 region: ${opt:stage, "us-west-2"}

functions:
 server:
   handler: lambda.server
   timeout: 30
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
  
resources:
  Resources:
    inventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PROVISIONED
        AttributeDefinitions: 
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "SK"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "PK"
            KeyType: "HASH"
          - AttributeName: "SK"
            KeyType: "RANGE"
        ProvisionedThroughput: 
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: inventory